---
- name: Generate Kubeconfig locally
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - "env/values.yaml"
  roles:
    - { role: gen-kubeconfig, tags: gen-kubeconfig }

## Distribute the Kubernetes Configuration Files
- name: Distribute the Controller kubeconfigs
  hosts: master
  remote_user: root
  tasks:
    - copy:
        src: "{{ playbook_dir }}/pki/certs/{{ item }}"
        dest: "~/"
      loop:
        - admin.kubeconfig
        - kube-controller-manager.kubeconfig
        - kube-scheduler.kubeconfig

- name: Distribute workers kubeconfigs
  hosts: worker
  remote_user: root
  tasks:
    - copy:
        src: "{{ playbook_dir }}/pki/certs/{{ item }}"
        dest: "~/"
      loop:
        - "{{ ansible_hostname }}.kubeconfig"
        - kube-proxy.kubeconfig
